version: "3"
services:
  mongo:
    ports:
      - 127.0.0.1:8232:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    container_name: mongo1
    volumes:
      - ./mongodb.key:/keyfile
      - ./mongo1_log:/bin/shell:z
    networks:
      - my-mongo-cluster2
    image: mongo:7
    # 容器启动时默认执行（默认用mongod）
    command: --replSet myReplicaSet --bind_ip_all --keyFile '/keyfile'
    # 检查容器是否健康运行
    healthcheck:
      test: ["CMD-SHELL", "mongosh --username admin --password admin --authenticationDatabase admin --eval 'try { rs.status() } catch (err) { rs.initiate() }' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
networks:
  my-mongo-cluster2:
    external: true
    name: my-mongo-cluster2